### ISSUE TITLE
env

### ISSUE THREAD

**Issue by Nicoleyk** [zsyasd/Excavating-RoI-Attention-for-Underwater-Object-Detection#5]
请问MMDetection == 2.20.0所需要的cuda版本是多少

**Comment by zsyasd** [comment]
请查阅mmdet官网。上面有非常详细的介绍。
![IMG_7899](https://github.com/user-attachments/assets/1bdbda2d-54a9-4ade-90eb-7b5a79a54a49)

**Comment by Nicoleyk** [comment]
![1728823303385](https://github.com/user-attachments/assets/ecceb6ff-2e24-4247-9066-b2a499711483)
n您知道这种错误怎么解决吗
